# -*- mode: python -*-
# OpenPGM build script
# $Id$

Import('snmphttp_env')
e = snmphttp_env.Copy()
e.Append(LIBS = ['libpgmplus', 'libpgmhttp', 'libpgmsnmp', 'libpgmex']);

# core preferred examples
e.Program(['pgmdump.c'])
e.Program(['pgmsend.c'])
e.Program(['pgmrecv.c'])
e.Program(['pgmping.c'])

# sync examples
e.Program(['blocksyncrecv.c'])
e.Program(['snonblocksyncrecv.c'])
e.Program(['pnonblocksyncrecv.c'])
e.Program(['enonblocksyncrecv.c'])
e.Program(['enonblocksyncrecvmsg.c'])
e.Program(['enonblocksyncrecvmsgv.c'])

# async examples
e.Program(['asyncqrecv.c'])
e.Program(['blockqrecv.c'])

ne = e.Copy()
ne.Append(LIBS = ['panel', 'ncurses']);
ne.Program(['pgmtop.c'])

# end of file
