message(STATUS "Detecting OpenPGM")
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/mkversion.c" _VERSION_H)
string(REGEX REPLACE ".*const unsigned pgm_major_version = ([0-9]+);.*" "\\1" OPENPGM_VERSION_MAJOR "${_VERSION_H}")
string(REGEX REPLACE ".*const unsigned pgm_minor_version = ([0-9]+);.*" "\\1" OPENPGM_VERSION_MINOR "${_VERSION_H}")
string(REGEX REPLACE ".*const unsigned pgm_micro_version = ([0-9]+);.*" "\\1" OPENPGM_VERSION_MICRO "${_VERSION_H}")
unset(_VERSION_H)
message(STATUS "Detecting OpenPGM - ${OPENPGM_VERSION_MAJOR}.${OPENPGM_VERSION_MINOR}.${OPENPGM_VERSION_MICRO}")

if(MSVC14)
	set(_pgm_COMPILER "-v140")
elseif(MSVC12)
	set(_pgm_COMPILER "-v120")
elseif(MSVC11)
	set(_pgm_COMPILER "-v110")
elseif(MSVC10)
	set(_pgm_COMPILER "-v100")
elseif(MSVC90)
	set(_pgm_COMPILER "-v90")
else()
	set(_pgm_COMPILER "")
endif()
