# -*- mode: python -*-
# OpenPGM build script
# $Id$

import os;
Import('env');
Import('snmphttp_env');
SConsignFile('scons.signatures');

env['CPPPATH'] = env['CPPPATH'] + [os.getcwd() + '/include'];
env['LIBPATH'] = env['LIBPATH'] + [os.getcwd() + '/ref/' + env['BUILD']];
snmphttp_env['CPPPATH'] = snmphttp_env['CPPPATH'] + [os.getcwd() + '/include'];
snmphttp_env['LIBPATH'] = snmphttp_env['LIBPATH'] + [os.getcwd() + '/ref/' + snmphttp_env['BUILD']];

SConscript('SConscript.libpgm');
SConscript('SConscript.libpgmex');
SConscript('SConscript.libpgmhttp');
SConscript('SConscript.libpgmsnmp');
SConscript('test/SConscript');
SConscript('dev/SConscript');
SConscript('examples/SConscript');

# end of file
