# -*- mode: python -*-
# OpenPGM build script
# $Id$

import os;
Import('env');
Import('xtenv');
SConsignFile('scons.signatures');

env['CPPPATH'] = env['CPPPATH'] + [os.getcwd() + '/include'];
env['LIBPATH'] = env['LIBPATH'] + [os.getcwd() + '/ref/' + env['BUILD']];
xtenv['CPPPATH'] = xtenv['CPPPATH'] + [os.getcwd() + '/include'];
xtenv['LIBPATH'] = xtenv['LIBPATH'] + [os.getcwd() + '/ref/' + xtenv['BUILD']];

SConscript('SConscript.libpgm');
SConscript('SConscript.libpgmex');
SConscript('SConscript.libpgmhttp');
SConscript('SConscript.libpgmsnmp');
SConscript('test/SConscript');
SConscript('dev/SConscript');
SConscript('examples/SConscript');

# end of file
