# -*- mode: python -*-
# OpenPGM build script
# $Id$

import os;
Import('env');
SConsignFile('scons.signatures');

env.ParseConfig('pkg-config --static --cflags --libs glib-2.0 gthread-2.0');
env['CPPPATH'] = env['CPPPATH'] + [os.getcwd() + '/include'];
env['LIBPATH'] = env['LIBPATH'] + [os.getcwd() + '/ref/' + env['BUILD']];

SConscript('SConscript.libpgm');
SConscript('SConscript.libpgmex');
SConscript('SConscript.libpgmhttp');
SConscript('SConscript.libpgmsnmp');
SConscript('test/SConscript');
SConscript('dev/SConscript');
SConscript('examples/SConscript');

# end of file
