# -*- mode: python -*-
# OpenPGM build script
# $Id$

EnsureSConsVersion( 0, 96 )

import os
env = Environment(ENV = os.environ,
	CCFLAGS = ['-pipe', '-g', '-Wall', '-pedantic', '-std=gnu99', '-D_REENTRANT'])

httpenv = env.Copy()
httpenv.ParseConfig('pkg-config --cflags --libs libsoup-2.2')

env.ParseConfig('pkg-config --cflags --libs glib-2.0')

shared_src = Split("""
		log.c
		pgm.c
""")

txw_obj = env.Object('txw.c')
if_obj  = env.Object('if.c')

shared_obj = []
for src in shared_src:
	shared_obj += env.Object(src)

env.Program(['pgmdump.c'] + shared_obj)
env.Program(['basic_send.c'] + shared_obj)
env.Program(['spm_idle.c'] + shared_obj)
env.Program(['stream_send.c'] + shared_obj)
httpenv.Program(['basic_recv.c'] + shared_obj)
httpenv.Program(['basic_http.c'] + shared_obj)
env.Program(['basic_container.c'])
env.Program(['basic_container2.c'])
env.Program(['basic_txw.c'] + txw_obj)
env.Program('basic_txw_byte', ['basic_txw.c', 'txw-byte.c'])
env.Program('basic_txw_bytep', ['basic_txw.c', 'txw-bytep.c'])
env.Program(['nak_txw.c'] + txw_obj)
env.Program(['stream_send_with_nak.c'] + shared_obj + txw_obj)
httpenv.Program(['basic_recv_with_nak.c'] + shared_obj)
env.Program(['dumpif.c'] + if_obj)
env.Program(['testif.c'] + if_obj)

# end of file
