# -*- mode: python -*-
# OpenPGM build script
# $Id$

EnsureSConsVersion( 0, 96 )

opt = Options(None, ARGUMENTS)
opt.AddOptions (
	(EnumOption ('BUILD', 'build environment', 'debug', ('release', 'debug', 'profile', 'thirtytwo'))),
)

import os
env = Environment(ENV = os.environ,
	CCFLAGS = ['-pipe', '-Wall', '-pedantic', '-std=gnu99', '-D_REENTRANT', '-DCONFIG_REED_SOLOMON_ENC8', '-DCONFIG_REED_SOLOMON_DEC8'],
	LINKFLAGS = ['-pipe']
)
opt.Update (env)

# define Builder for translating HTML documents for inlining.
bld = Builder(action = './htdocs/convert_to_macro.pl $SOURCE > $TARGET')
env.Append(BUILDERS = {'HtmlC' : bld})

# Define separate build environments
release = env.Copy(BUILD = 'release')
release.Append(CCFLAGS = '-O2')

debug = env.Copy(BUILD = 'debug')
debug.Append(CCFLAGS = '-ggdb', LINKFLAGS = '-gdb')

profile = env.Copy(BUILD = 'profile')
profile.Append(CCFLAGS = ['-O2','-pg'], LINKFLAGS = '-pg')

thirtytwo = release.Copy(BUILD = 'thirtytwo')
thirtytwo.Append(CCFLAGS = '-m32', LINKFLAGS = '-m32')

# choose and environment to build
if env['BUILD'] == 'release':
	Export({'env':release})
elif env['BUILD'] == 'profile':
	Export({'env':profile})
elif env['BUILD'] == 'thirtytwo':
	Export({'env':thirtytwo})
else:
	Export({'env':debug})

Import('env')
ref_node = 'ref/' + env['BUILD'] + '/';
BuildDir(ref_node, '.', duplicate=0)
SConscript(ref_node + 'SConscript')

# end of file
