# -*- mode: python -*-
# OpenPGM build script
# $Id$

import os
Import('env')

e = env.Clone()
e.Append(LIBS = ['libpgmplus', 'libpgmex']);

e.Program(['basic_send.c'])
e.Program(['spm_idle.c'])
e.Program(['stream_send.c'])
e.Program(['basic_container.c'])
e.Program(['basic_container2.c'])
e.Program(['basic_txw.c'])
e.Program(['nak_txw.c'])
e.Program(['stream_send_with_nak.c'])
e.Program(['dumpif.c'])
e.Program(['testif.c'])
e.Program('sw_calc.c')
e.Program(['basic_rxw.c'])
e.Program('test_cpu_timers.c')
e.Program(['test_time.c'])
e.Program(['block_send.c'])
e.Program(['test_rs.c'])
e.Program(['test_rs2.c'])
e.Program(['sock_name.c'])
e.Program(['pgmversion.c'])

# merge SNMP and LIBSOUP libraries into new environment
me = e.Clone();
me.MergeFlags(me['SNMP_FLAGS']);
me.MergeFlags(me['LIBSOUP_FLAGS']);

me.Program(['basic_recv.c'])
me.Program(['basic_http.c'])
me.Program(['basic_recv_with_nak.c'])
me.Program(['basic_recv_with_rxw.c'])


# end of file
