# -*- mode: python -*-
# OpenPGM build script
# $Id$

Import('env')
e = env.Copy(
		LIBS = env['LIBS'] + ['libpgm'],
		);

e.Program(['pgmdump.c'])
e.Program(['pgmsend.c'])
e.Program(['pgmrecv.c'])
e.Program(['pgmping.c'])

ne = e.Copy(
		LIBS = e['LIBS'] + ['panel', 'ncurses'],
		);

ne.Program(['pgmtop.c'])

# end of file
