# -*- mode: python -*-
# OpenPGM build script
# $Id$

Import('env')
e = env.Copy()
e.ParseConfig('pkg-config --cflags --libs glib-2.0 gthread-2.0 libsoup-2.2')
e.Append(
		LIBS = env['LIBS'] + env['NETSNMP_LIBS'] + ['libpgm', 'libpgmhttp', 'libpgmsnmp', 'libpgmex'],
	);

e.Program(['pgmdump.c'])
e.Program(['pgmsend.c'])
e.Program(['pgmrecv.c'])
e.Program(['pgmping.c'])

e.Program(['syncrecv.c'])

ne = e.Copy(
		LIBS = e['LIBS'] + ['panel', 'ncurses'],
		);

ne.Program(['pgmtop.c'])

# end of file
