# -*- mode: python -*-
# OpenPGM build script
# $Id$

Import('env')
e = env.Clone();
e.Append(LIBS = ['libpgm', 'libpgmex']);

e.Program(['monitor.c', 'dump-json.c'])
e.Program(['app.c'])
e.Program(['sim.c', 'dump-json.c'])

# end of file
