# -*- mode: python -*-
# OpenPGM build script
# $Id$

import os
Import('env')
Import('snmphttp_env')

e = env.Copy()
e.Append(LIBS = ['libpgmplus', 'libpgmex']);

httpe = snmphttp_env.Copy()
httpe.Append(LIBS = ['libpgmplus', 'libpgmex']);

# source:

httpe.Program(['basic_recv.c'])
httpe.Program(['basic_http.c'])
httpe.Program(['basic_recv_with_nak.c'])
httpe.Program(['basic_recv_with_rxw.c'])

e.Program(['basic_send.c'])
e.Program(['spm_idle.c'])
e.Program(['stream_send.c'])
e.Program(['basic_container.c'])
e.Program(['basic_container2.c'])
e.Program(['basic_txw.c'])
e.Program(['nak_txw.c'])
e.Program(['stream_send_with_nak.c'])
e.Program(['dumpif.c'])
e.Program(['testif.c'])
e.Program('sw_calc.c')
e.Program(['basic_rxw.c'])
e.Program('test_cpu_timers.c')
e.Program(['test_time.c'])
e.Program(['block_send.c'])
e.Program(['test_rs.c'])
e.Program(['sock_name.c'])

# end of file
