# -*- mode: python -*-
# OpenPGM build script
# $Id$

import os;
Import('env');

env.Append(CPPPATH = os.getcwd() + '/include');
env.Append(LIBPATH = os.getcwd() + '/ref/' + env['BUILD']);

SConscript('SConscript.libpgm');
SConscript('SConscript.libpgmex');
SConscript('SConscript.libpgmhttp');
SConscript('SConscript.libpgmsnmp');
SConscript('test/SConscript');
SConscript('dev/SConscript');
SConscript('examples/SConscript');

# unit testing framework optional.
#if env['CHECK'] == 1:
# 	SConscript('check/SConscript');

# end of file
