# -*- mode: python -*-
# OpenPGM build script
# $Id$

import os
Import('env')

e = env.Clone()
e.Append(LIBS = ['libpgm', 'libpgmex']);

e.Program(['basic_send.c'])
e.Program(['spm_idle.c'])
e.Program(['stream_send.c'])
e.Program(['basic_container.c'])
e.Program(['basic_container2.c'])
e.Program(['basic_txw.c'])
e.Program(['nak_txw.c'])
e.Program(['stream_send_with_nak.c'])
e.Program(['dumpif.c'])
e.Program(['testif.c'])
e.Program('sw_calc.c')
e.Program(['basic_rxw.c'])
e.Program(['test_time.c'])
e.Program(['block_send.c'])
e.Program(['test_rs.c'])
e.Program(['test_rs2.c'])
e.Program(['sock_name.c'])
e.Program(['pgmversion.c'])
e.Program(['test_partial_csum.c'])

# merge SNMP and LIBSOUP libraries into new environment

if e['WITH_SNMP'] == 'true' or e['WITH_HTTP'] == 'true':
	me = e.Clone();
	if me['WITH_SNMP'] == 'true':
		me.MergeFlags(me['SNMP_FLAGS']);
	if me['WITH_HTTP'] == 'true':
		me.MergeFlags(me['LIBSOUP_FLAGS']);
	me.Program(['basic_recv.c'])
	me.Program(['basic_http.c'])
	me.Program(['basic_recv_with_nak.c'])
	me.Program(['basic_recv_with_rxw.c'])

uname_s = os.uname()[0];
if uname_s == 'Linux':
	e.Program('test_cpu_timers.c')

# end of file
