/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf,v 5.3 2004/04/15 12:29:19 dts12 Exp $
 */

#ifndef __PGM_MIB_H__
#define __PGM_MIB_H__

#include <glib.h>

G_BEGIN_DECLS

/* function declarations */
gboolean pgm_mib_init (GError**);

int send_pgmStart_trap(void);
int send_pgmStop_trap(void);
int send_pgmNewSourceTrap_trap(void);
int send_pgmClosedSourceTrap_trap(void);
int send_pgmNewReceiverTrap_trap(void);
int send_pgmClosedReceiverTrap_trap(void);
int send_pgmNakFailuresTrap_trap(void);
int send_pgmNewDlrSourceTrap_trap(void);
int send_pgmClosedDlrSourceTrap_trap(void);

G_END_DECLS

#endif /* __PGM_MIB_H__ */
