# -*- mode: python -*-
# OpenPGM build script
# $Id$

Import('snmphttp_env')
e = snmphttp_env.Copy()
e.Append(LIBS = ['libpgm', 'libpgmhttp', 'libpgmsnmp', 'libpgmex']);

e.Program(['pgmdump.c'])
e.Program(['pgmsend.c'])
e.Program(['pgmrecv.c'])
e.Program(['pgmping.c'])

e.Program(['syncrecv.c'])

ne = e.Copy()
ne.Append(LIBS = ['panel', 'ncurses']);
ne.Program(['pgmtop.c'])

# end of file
