# -*- mode: python -*-
# OpenPGM build script
# $Id$

Import('env')
e = env.Clone();
e.ParseConfig('pkg-config --static --cflags --libs check');

e2 = e.Clone();
e2.Append(LIBS = ['libpgm', 'libpgmex']);
e2.Program('check_pgm', ['check_pgm.c', 'check_send.c', 'check_if.c'])

e3 = e.Clone();
e2.Append(LIBS = ['libpgmplus', 'libpgmex']);
e2.Program('check_pgmplus', ['check_pgm.c', 'check_send.c', 'check_if.c'])

# end of file
